
POST  https://resepai-backend-vlbqdtksba-uc.a.run.app/v/login

{
    "name" : "adi",
    "password" : "1234"
}

###

POST https://resepai-backend-vlbqdtksba-uc.a.run.app/v/regis

{
    "name" : "etus",
    "password" : "etus1234",
    "notlp" : "924i91",
    "alamat" : "jalan kaki"
}

###

GET https://resepai-backend-vlbqdtksba-uc.a.run.app/v/account

###

GET https://resepai-backend-vlbqdtksba-uc.a.run.app/v/account/3

###

PUT https://resepai-backend-vlbqdtksba-uc.a.run.app/v/account/5

{
    "name" : "jason",
    "password" : "5454",
    "notlp" : "924i3241",
    "alamat" : "jalani saja dulu"
}

###
DELETE https://resepai-backend-vlbqdtksba-uc.a.run.app/v/account/5

